## Importing The Libraries

In [25]:
import pandas as pd
import numpy as np

## Loading The Data in an Instance

In [26]:
Breast = pd.read_csv("Breast_cancer.csv")
Breast.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

### M = Malignant(Cancerous)  && B = Banign (noncancerous)

In [27]:
Breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

Breast.size

In [28]:
Breast.drop('Unnamed: 32', axis=1, inplace=True)
Breast.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000   
mean        0.181162  ...     16.269190      25.677223       107.261213   
std         0.027414  ...      4.833242       6.146258        33.602542   
min         0.106000  ...      7.930000      12.020000        50.410000   
25%         0.161900  ...     13.010000      21.080000        84.110000   
50%         0.179200  ...     14.970000      25.410000        97.660000   
75%         0.195700  ...     18.790000      29.720000       125.400000   
max         0.304000  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 31 columns]

In [29]:
Breast['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

## Always Ask 6 Questions to your Data

In [30]:
Breast.shape

(569, 32)

In [31]:
Breast.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [32]:
Breast.duplicated().sum()

np.int64(0)

## Encoding the Target Variables

In [33]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()

### map() function is used to replace the data points

In [34]:
Breast['diagnosis'] = Breast['diagnosis'].map({'M':1, 'B':0})

In [35]:
Breast['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

## Splitting Data Into Training and Testing DataSets

In [36]:
X = Breast.drop('diagnosis',axis =1)  # Beacuase on x axis we want all the other parameters as an input
Y = Breast['diagnosis']  # We want diagnosis as an output on y axix which we are basically trying to predict

In [37]:
print(X.shape,Y.shape)

(569, 31) (569,)


In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [39]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((455, 31), (114, 31), (455,), (114,))

## Standard Scaling (Bringing All the values in a specified Range)

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [41]:
sc.fit(X_train)

StandardScaler()

In [42]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

X_train

array([[-0.23712699, -1.44075296, -0.43531947, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [-0.23702031,  1.97409619,  1.73302577, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-0.23712907, -1.39998202, -1.24962228, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [-0.17630431,  0.04880192, -0.55500086, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.23675669, -0.03896885,  0.10207345, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.2371006 , -0.54860557,  0.31327591, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

## Trainging The Model (Classification Problem) or (Logistic Regression)

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
lg = LogisticRegression()

In [44]:
lg.fit(X_train,Y_train)     ## X_train is the input and Y_train is the output
prediction = lg.predict(X_test)  ## X_test is the input and we are predicting the output and storing it in prediction variable

prediction

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1])

In [45]:
str(accuracy_score(Y_test,prediction)*100) + "%"

'97.36842105263158%'

## Creating Prediction System

In [46]:
X_test[10]    ## This is the 10th row of the X_test data
                ##Take it as an Input and predict the output

array([-0.17478099, -0.25698012,  1.42326216, -0.32031902, -0.32851959,
       -0.56328674, -0.98390686, -0.77069479, -0.72596174, -0.69922504,
       -0.96042428, -0.68451875,  0.27222162, -0.74640146, -0.47666829,
       -0.39989692, -0.94442957, -0.55196315, -0.86571951, -0.87021209,
       -0.71566322, -0.39224142,  1.43507375, -0.47432767, -0.43045164,
       -0.11415698, -0.94573859, -0.64825719, -0.82955846, -0.73083204,
       -0.89676905])

In [47]:
input_text = (-0.17478099, -0.25698012,  1.42326216, -0.32031902, -0.32851959,
       -0.56328674, -0.98390686, -0.77069479, -0.72596174, -0.69922504,
       -0.96042428, -0.68451875,  0.27222162, -0.74640146, -0.47666829,
       -0.39989692, -0.94442957, -0.55196315, -0.86571951, -0.87021209,
       -0.71566322, -0.39224142,  1.43507375, -0.47432767, -0.43045164,
       -0.11415698, -0.94573859, -0.64825719, -0.82955846, -0.73083204,
       -0.89676905)
np_df = np.asarray(input_text)
prediction = lg.predict(np_df.reshape(1,-1))
if prediction[0] ==1:
    print("cancerous Breast")
else:
    print("Not Cancerous")

Not Cancerous


In [48]:
import pickle ## This is used to save the model
pickle.dump(lg, open('cancer.pkl','wb'))  ## wb is write binary
